name: Run Test

on:
  push:
    branches:
      - develop
      - master
    paths:
      - '**.go'
  pull_request:
    types:
      - opened
    paths:
      - '**.go'
jobs:
  go-test:

    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - name: Set up Go 1.16.6
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.6

      - name: Check out code
        uses: actions/checkout@v2

      - name: Run checks
        uses: golangci/golangci-lint-action@v2
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest
          args: --timeout=5m

          # Optional: working directory, useful for monorepos
          # working-directory: somedir

          # Optional: golangci-lint command line arguments.
          # args: --issues-exit-code=0

          # Optional: show only new issues if it's a pull request. The default value is `false`.
          # only-new-issues: true

          # Optional: if set to true then the action will use pre-installed Go.
          skip-go-installation: true

          # Optional: if set to true then the action don't cache or restore ~/go/pkg.
          # skip-pkg-cache: true

          # Optional: if set to true then the action don't cache or restore ~/.cache/go-build.
          # skip-build-cache: true

      - name: Run tests
        run: go test -race ./...